### ISSUE TITLE
unable to get kill-ring to work in vi-mode

### ISSUE THREAD

**Issue by nerd190** [marlonrichert/zsh-edit#6]
First, thank you! such a great plugin!!
The kill-ring works out-the-box on emacs mode but unable to on vi-mode, is there a way?
Thanks again!

**Comment by marlonrichert** [comment]
Yes, there is a way, but I need to implement it first. Coming soon.™ 🙂

**Comment by marlonrichert** [comment]
All right, it's there. Enjoy!

---

If you use my software on a regular basis, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

**Comment by nerd190** [comment]
Thank you @marlonrichert !!!
I have a problem, was wondering if it is the same for you too?

```bash
~ ❯ zsh -f     # No Configs.
% bindkey -v   # Vi Binds.
% source ~/zsh-edit/zsh-edit.plugin.zsh  # Awesomeness!
# Add to killring:
% aaa<ESC>yy
% bbb<ESC>Vy
% ccc<ESC>dd
% ddd<ESC>Vd
# Bindings:
% bindkey -M vicmd '^Y' yank-pop    # Ctrl+y
% bindkey -M vicmd '^[y' reverse-yank-pop    # Alt+y
% <ESC><C-Y>
aaa  bbb  ccc  ddd
```

Looks great! but unfortunately, subsequent keypresses (Ctrl+y/Alt+y) do not cycle the killring,  but if I was to:

```bash
# Map "y" to "yank" instead of "vi-yank":
bindkey -M vicmd y yank
```

It will work perfectly, only problem is that emacs "yank" doesnt accept vi motions.

Thank you again for adding vi support, its really appreciated!

**Comment by marlonrichert** [comment]
> unfortunately, subsequent keypresses (Ctrl+y/Alt+y) do not cycle the killring

[As mentioned in the Readme](https://github.com/marlonrichert/zsh-edit#clipboard-viewer), pressing (`reverse-`)`yank-pop` by itself merely shows the current contents of the kill ring. It doesn't insert anything.

In `vi` mode, you need to first use `vi-put-before` or `vi-put-after`, so that you actually paste a kill into the command line. After that, you can cycle through the kill ring with `yank-pop` and `reverse-yank-pop`.
